<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=11"/>
<meta name="generator" content="Doxygen 1.14.0"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>RoboDBG: error_already_set Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<script type="text/javascript" src="clipboard.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript" src="cookie.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr id="projectrow">
  <td id="projectalign">
   <div id="projectname">RoboDBG
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.14.0 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search/",'.html');
</script>
<script type="text/javascript">
$(function() { codefold.init(); });
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search',true);
  $(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(function(){initNavTree('classerror__already__set.html','','classerror__already__set-members'); });
</script>
<div id="container">
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<div id="MSearchResults">
<div class="SRPage">
<div id="SRIndex">
<div id="SRResults"></div>
<div class="SRStatus" id="Loading">Loading...</div>
<div class="SRStatus" id="Searching">Searching...</div>
<div class="SRStatus" id="NoMatches">No Matches</div>
</div>
</div>
</div>
</div>

<div class="header">
  <div class="headertitle"><div class="title">error_already_set Class Reference</div></div>
</div><!--header-->
<div class="contents">

<p>Fetch and hold an error which was already set in Python. An instance of this is typically thrown to propagate python-side errors back through C++ which can either be caught manually or else falls back to the function dispatcher (which then raises the captured error back to python).  
 <a href="#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="pytypes_8h_source.html">pytypes.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for error_already_set:</div>
<div class="dyncontent">
 <div class="center">
  <img src="classerror__already__set.png" alt=""/>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 id="header-pub-methods" class="groupheader"><a id="pub-methods" name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a9f6456fb9f03460d943682037132e819" id="r_a9f6456fb9f03460d943682037132e819"><td class="memItemLeft" align="right" valign="top"><a id="a9f6456fb9f03460d943682037132e819" name="a9f6456fb9f03460d943682037132e819"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>error_already_set</b> ()</td></tr>
<tr class="memdesc:a9f6456fb9f03460d943682037132e819"><td class="mdescLeft">&#160;</td><td class="mdescRight">Fetches the current Python exception (using PyErr_Fetch()), which will clear the current Python error indicator. <br /></td></tr>
<tr class="memitem:ab1aae3b3af73df4464e67f45a53bf140" id="r_ab1aae3b3af73df4464e67f45a53bf140"><td class="memItemLeft" align="right" valign="top"><a id="ab1aae3b3af73df4464e67f45a53bf140" name="ab1aae3b3af73df4464e67f45a53bf140"></a>
const char *&#160;</td><td class="memItemRight" valign="bottom"><b>what</b> () const noexcept override</td></tr>
<tr class="memdesc:ab1aae3b3af73df4464e67f45a53bf140"><td class="mdescLeft">&#160;</td><td class="mdescRight">The <a class="el" href="#ab1aae3b3af73df4464e67f45a53bf140" title="The what() result is built lazily on demand. WARNING: This member function needs to acquire the Pytho...">what()</a> result is built lazily on demand. WARNING: This member function needs to acquire the Python GIL. This can lead to crashes (undefined behavior) if the Python interpreter is finalizing. <br /></td></tr>
<tr class="memitem:a751b231e5c796447d867cf30007a7fc0" id="r_a751b231e5c796447d867cf30007a7fc0"><td class="memItemLeft" align="right" valign="top"><a id="a751b231e5c796447d867cf30007a7fc0" name="a751b231e5c796447d867cf30007a7fc0"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>restore</b> ()</td></tr>
<tr class="memdesc:a751b231e5c796447d867cf30007a7fc0"><td class="mdescLeft">&#160;</td><td class="mdescRight">Restores the currently-held Python error (which will clear the Python error indicator first if already set). NOTE: This member function will always restore the normalized exception, which may or may not be the original Python exception. WARNING: The GIL must be held when this member function is called! <br /></td></tr>
<tr class="memitem:a7dad9b92f8d2132d1f627ea9329c7aeb" id="r_a7dad9b92f8d2132d1f627ea9329c7aeb"><td class="memItemLeft" align="right" valign="top"><a id="a7dad9b92f8d2132d1f627ea9329c7aeb" name="a7dad9b92f8d2132d1f627ea9329c7aeb"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>discard_as_unraisable</b> (<a class="el" href="classobject.html">object</a> err_context)</td></tr>
<tr class="memdesc:a7dad9b92f8d2132d1f627ea9329c7aeb"><td class="mdescLeft">&#160;</td><td class="mdescRight">If it is impossible to raise the currently-held error, such as in a destructor, we can write it out using Python's unraisable hook (<span class="tt">sys.unraisablehook</span>). The error context should be some object whose <span class="tt">repr()</span> helps identify the location of the error. Python already knows the type and value of the error, so there is no need to repeat that. <br /></td></tr>
<tr class="memitem:ad672bc258e8d563bbfbeb7a0817d1608" id="r_ad672bc258e8d563bbfbeb7a0817d1608"><td class="memItemLeft" align="right" valign="top"><a id="ad672bc258e8d563bbfbeb7a0817d1608" name="ad672bc258e8d563bbfbeb7a0817d1608"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>discard_as_unraisable</b> (const char *err_context)</td></tr>
<tr class="memdesc:ad672bc258e8d563bbfbeb7a0817d1608"><td class="mdescLeft">&#160;</td><td class="mdescRight">An alternate version of <span class="tt"><a class="el" href="#a7dad9b92f8d2132d1f627ea9329c7aeb" title="If it is impossible to raise the currently-held error, such as in a destructor, we can write it out u...">discard_as_unraisable()</a></span>, where a string provides information on the location of the error. For example, <span class="tt">__func__</span> could be helpful. WARNING: The GIL must be held when this member function is called! <br /></td></tr>
<tr class="memitem:a471237e45e4049e9e9ec4bc049621eb1" id="r_a471237e45e4049e9e9ec4bc049621eb1"><td class="memItemLeft" align="right" valign="top"><a id="a471237e45e4049e9e9ec4bc049621eb1" name="a471237e45e4049e9e9ec4bc049621eb1"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>clear</b> ()</td></tr>
<tr class="memitem:a6585d62b1153c401745df155a7c87f6f" id="r_a6585d62b1153c401745df155a7c87f6f"><td class="memItemLeft" align="right" valign="top"><a id="a6585d62b1153c401745df155a7c87f6f" name="a6585d62b1153c401745df155a7c87f6f"></a>
bool&#160;</td><td class="memItemRight" valign="bottom"><b>matches</b> (<a class="el" href="classhandle.html">handle</a> exc) const</td></tr>
<tr class="memdesc:a6585d62b1153c401745df155a7c87f6f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the currently trapped error type matches the given Python exception class (or a subclass thereof). May also be passed a tuple to search for any exception class matches in the given tuple. <br /></td></tr>
<tr class="memitem:a837ac3c84def45be3a018e796e7c8b28" id="r_a837ac3c84def45be3a018e796e7c8b28"><td class="memItemLeft" align="right" valign="top"><a id="a837ac3c84def45be3a018e796e7c8b28" name="a837ac3c84def45be3a018e796e7c8b28"></a>
const <a class="el" href="classobject.html">object</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>type</b> () const</td></tr>
<tr class="memitem:a8338c35feee04b20a745ac7123e2dc81" id="r_a8338c35feee04b20a745ac7123e2dc81"><td class="memItemLeft" align="right" valign="top"><a id="a8338c35feee04b20a745ac7123e2dc81" name="a8338c35feee04b20a745ac7123e2dc81"></a>
const <a class="el" href="classobject.html">object</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>value</b> () const</td></tr>
<tr class="memitem:a7df5afe2a73db865aa754f7affe751ff" id="r_a7df5afe2a73db865aa754f7affe751ff"><td class="memItemLeft" align="right" valign="top"><a id="a7df5afe2a73db865aa754f7affe751ff" name="a7df5afe2a73db865aa754f7affe751ff"></a>
const <a class="el" href="classobject.html">object</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>trace</b> () const</td></tr>
</table>
<a name="details" id="details"></a><h2 id="header-details" class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Fetch and hold an error which was already set in Python. An instance of this is typically thrown to propagate python-side errors back through C++ which can either be caught manually or else falls back to the function dispatcher (which then raises the captured error back to python). </p>
</div><hr/>The documentation for this class was generated from the following files:<ul>
<li><a class="el" href="pytypes_8h_source.html">pytypes.h</a></li>
<li><a class="el" href="pybind11_8h_source.html">pybind11.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<div id="page-nav" class="page-nav-panel">
<div id="page-nav-resize-handle"></div>
<div id="page-nav-tree">
<div id="page-nav-contents">
</div><!-- page-nav-contents -->
</div><!-- page-nav-tree -->
</div><!-- page-nav -->
</div><!-- container -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a href="classerror__already__set.html">error_already_set</a></li>
    <li class="footer">Generated by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.14.0 </li>
  </ul>
</div>
</body>
</html>
